server:
  host: "localhost"
  port: 8080
  tls:
    enabled: false

downloadPath: "~/Downloads"  # Directory to save downloaded files

logging:
  level: info 
  format: json

debug: true

openai:
  apiKey: "${OPENAI_API_KEY}"  # OpenAI API key
  baseUrl: "https://api.openai.com/v1"  # OpenAI Base API URL
  model: "gpt-4o" # Model to use for OpenAI API